#!/usr/bin/env php
<?php

use Mmi\Console\Application;

if (PHP_SAPI !== 'cli') {
    echo 'Must be run as a CLI application';
    exit(1);
}

set_time_limit(0);

/**
 * @var Composer\Autoload\ClassLoader $loader
 */
//określanie ścieżki
define('BASE_PATH', realpath(dirname(__FILE__)) . '/../');

$loader = require BASE_PATH . 'vendor/autoload.php';

$application = new Application();
$application->run();
